name: Deploy dev environment

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout the project
        uses: actions/checkout@v2
        with:
          ref: develop
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.BASE_URL_PROD }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - 
        name: Build and push to the registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.BASE_URL_PROD }}/wiki-service:latest
